### ISSUE TITLE
Incompatibility with nodejs 7.x?

### ISSUE THREAD

**Issue by vladdancer** [drupalway/vmgen#1]
env:
os: OS X El Capitan (10.11.6)
node --version => v7.2.0
npm --version => v3.10.9

When I try `vmgen my_project 7` I get:
> (node:2278) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:2278) DeprecationWarning: Calling an asynchronous function without callback is deprecated.

`vm` folder created but with empty `config.yml`.

**Comment by valentine94** [comment]
Probably some of modules, which uses for making templates aren't supports this version, will take a look

**Comment by valentine94** [comment]
Fixed now, thanks
